# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Frey/Desktop/MyLab1/MyLab1.cache/wt [current_project]
set_property parent.project_path C:/Users/Frey/Desktop/MyLab1/MyLab1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Frey/Desktop/MyLab1/MyLab1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/function.vh
read_verilog -library xil_defaultlib {
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/ALU.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/CPUTEST.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/Code2Inst.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/CtrlUnit.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/Font816.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/HazardDetectionUnit.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/ImmGen.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/common/MUX2T1_32.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/common/MUX4T1_32.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/fix/RAM_B.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/common/REG32.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/REG_EX_MEM.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/REG_ID_EX.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/REG_IF_ID.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/REG_MEM_WB.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/fix/ROM_D.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/RV32core.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/core/Regs.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/VGATEST.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/common/add_32.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/btn_scan.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/clk_diff.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/common/cmp_32.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/debug_clk.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/display.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/my_clk_gen.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/parallel2serial.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/vga.v
  C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/sources_1/imports/design_sources/auxillary/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/constrs_1/imports/constraint_sources/constraint.xdc
set_property used_in_implementation false [get_files C:/Users/Frey/Desktop/MyLab1/MyLab1.srcs/constrs_1/imports/constraint_sources/constraint.xdc]


synth_design -top top -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
